import type { Metadata } from "next";

import { League_Spartan } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-league-spartan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.variable} antialiased`}>
        <div className="w-full h-24 bg-primary">
          <picture>
            {/* Mobile Image */}
            <source
              media="(max-width: 375px)"
              src="/images/bg-header-mobile.svg"
            />
            {/* Desktop Image */}
            <source
              media="(min-width: 376px)"
              src="/images/bg-header-desktop.svg"
            />
            {/* Fallback */}
            <Image
              src="/images/bg-header-desktop.svg"
              alt="background"
              height={0}
              width={0}
              style={{ width: "100%", height: "100%" }}
            />
          </picture>
        </div>
        {children}
      </body>
    </html>
  );
}
